[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

[template.environment]
  META_TITLE = ""
  META_URL = ""
  META_DESC = ""
  META_LANG = "en"
  META_EMAIL = ""
  META_PHONE = ""

[[redirects]]
  from = "*"
  to = "/404"
  status = 404
